### ISSUE TITLE
Analytical solution for fluvial incision with the advection equation

### ISSUE THREAD

**Issue by KReinmoeller** [BCampforts/evolving_landscapes#1]
Hi :) 
I fell a little behind yesterday and am on the fluvial incision with the advection equation. I’m stuck in trying to calculate an analytical solution. Hopefully I can get some guidance. Thank you!

I've defined the advection_solver, and have defined the terms.
```
L = 15000
dx = 100
nb_cells = int(L/dx)
x=np.linspace(0,15000,nb_cells)
z=np.ones(nb_cells)*75
z[-1]= 0

v = -1 # m/yr
run_duration = 10000 #yrs
dt = 0.9 * dx / abs(v)
```
The next step is to calcuate the analytical solution for comparison but I'm stuck.

```
z_ini = np.array(z)
z_ana = np.array(z)
z_ana = np.array(nb_cells)*75
```

**Comment by BCampforts** [comment]
Hint: Start by calculating the location of the knickpoint (waterfall) after 10.000 years. Remember that you know the propagation speed (velocity) and that the advection equation is an initial value problem where the initial configuration shifts forwards or backwards in time.

**Comment by KReinmoeller** [comment]
Hi :) 
I'm working on the "Adjusting fluvial incision to be mass conservative" of the Stream Power Law notebook and I'm trying to add a uplift rate of 1 m per Myr. I added `U ` to the solver and define in later on as `U = np.ones(nb_cells)*1e-3` (which I had help with) but now I get an error message saying that '`T_num' is not defined`. 
I'm guessing that I didn't make the solver correctly (below). Hopefully I can get some help!

```
def stream_power_solver(T_num, v, dt, dx, run_duration, U):
    iteration = 0
    while iteration*dt < run_duration:
        iteration += 1
        if v[-1] > 0:
            T_num[1:] = T_num[1:]-(v[1:]*dt/dx)*(T_num[1:]-T_num[:-1])+U
        if v[-1] < 0:
            T_num[:-1] = T_num[:-1]-(v[:-1]*dt/dx)*(T_num[1:]-T_num[:-1])+U 
    return T_num
```

**Comment by BCampforts** [comment]
Hi, 

Can you show the entire code, including the part where you call the function? 
Thanks!

**Comment by KReinmoeller** [comment]
Hi, thank you for your reply! Here it is the rest of the code, apologies for the late response.
```
nb_cells = 151
L = 15000
dx = L / (nb_cells-1)
print('dx is %i m'%dx)

x=np.linspace(0,L,nb_cells)
z=np.ones(nb_cells)*70
z[-1]= 0

A = (x ** 1.5) + dx 
K = 5e-4
m = 0.5
v = -K * (A**m)
U = np.ones(nb_cells)*1e-3 #in mm/yr

dt = 0.5*dx/max(abs(v))
print('dt is %.02f year'%dt)

#Question
run_duration = 100000
z_num = stream_power_solver(T_num, v, dt, dx, run_duration, U)
plt.plot(x/1000,z_num)
```

**Comment by MGraaff** [comment]
In the second to last line, where you call the stream_power_solver function, you use T_num as the variable it needs to use to calculate z_num. But the name T_num is a placeholder for within the function and is not defined outside of it.. You want to use z_num as the input variable in its place, so the second to last line should be:
`z_num = stream_power_solver(z_num, v, dt, dx, run_duration, U)`

**Comment by KReinmoeller** [comment]
Hey, that makes sense but I receive a value error message saying that; 
```
Cell In[8], line 22
     19 #Assignment
     21 run_duration = 100000
---> 22 z_num = stream_power_solver(z_num,v,dt,dx,run_duration,U)
     23 plt.plot(x/1000,z_num)

Cell In[6], line 9, in stream_power_solver(T_num, v, dt, dx, run_duration, U)
      7         T_num[1:] = T_num[1:]-(v[1:]*dt/dx)*(T_num[1:]-T_num[:-1])+U 
      8     if v[-1] < 0:
----> 9         T_num[:-1] = T_num[:-1]-(v[:-1]*dt/dx)*(T_num[1:]-T_num[:-1])+U
     10 return T_num
ValueError: operands could not be broadcast together with shapes (150,) (151,) 
```
I thought that it's because I haven't defined z_num and tried z instead but I still get the same error message. Do you maybe have any other suggestions? Thank you!

**Comment by BCampforts** [comment]
Almost there. You pass `U` as an array to the function. Either make `U` a scalar (`U = 1e-3 #in mm/yr`;  possible here because U is constant in space for this exercise) or adjust the solution to consider only the cells you calculate with (`U[1:]` on line 7 and `U[:-1]` on line 9)

**Comment by KReinmoeller** [comment]
It worked! Thank you so much!
