### ISSUE TITLE
Graphs do not plot?

### ISSUE THREAD

**Issue by T-Bosch** [BCampforts/evolving_landscapes#2]
I wanted to plot both the upwind and downwind solution (so I could get the pdf-file). But, without changing anything about the codes, nothing is being plotted?

Any help?

**Comment by PeterHegeman** [comment]
If you are using:
"if iteration % 1e5 == 0:"
You could try to lower the 1e5 value.

**Comment by T-Bosch** [comment]
> If you are using: "if iteration % 1e5 == 0:" You could try to lower the 1e5 value.

Thanks! I changed it into 75. Probably because the CFL was changed into dt = 0.9*dx/v. Now it works!
